## Capacitación - Python básico II (modules: numpy y pandas)

==========================================================================================

#### Numpy (library for calculation using Mutidimensional arrays)

In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5]) 
print(my_array)

Shape

In [ ]:
print(my_array.shape)

In [ ]:
my_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]) 
print(my_array)

In [ ]:
print(my_array.shape)

Reshape

In [ ]:
aux = np.array([1, 2, 3, 4, 5, 6]) 
my_array = aux.reshape((3, 2))
print(my_array)

In [ ]:
my_array = aux.reshape(2,-1)
print(my_array)

In [ ]:
my_array = aux.reshape((3, 2), order = 'F')
print(my_array)

Indexing

In [ ]:
my_array = np.array([1, 2, 3, 4, 5, 6])
print(my_array[0]) 
print(my_array[1]) 

In [ ]:
my_array[0] = -1 
print(my_array)

Creating array

In [ ]:
np.empty([2,3], dtype = int)

In [ ]:
my_new_array = np.zeros([2,3]) 
print(my_new_array)

In [ ]:
my_new_array = np.ones([2,3]) 
print(my_new_array)

In [ ]:
my_random_array = np.random.random([3,4]) 
print(my_random_array)

In [ ]:
a = 10
b = 20
a = np.floor(a + b*np.random.random((3,4))) 
print(a)

In [ ]:
np.arange( 10, 30, 5) # similar to range (start, stop, by)

In [ ]:
list(np.arange( 10, 30, 5 ))

Slicing

In [ ]:
my_array2 = np.array([3, 2, 8, 22, 127]) 
my_array2

In [ ]:
my_array2 = np.array([3, 2, 8, 22, 127]) 
print(my_array2[1:])

In [ ]:
my_array2 = np.array([3, 2, 8, 22, 127]) 
print(my_array2[2:4])

Multidimensional

In [ ]:
my_array = np.array([[4, 5], [6, 1]])
my_array

In [ ]:
print(my_array[0][1])

In [ ]:
my_array_column_2 = my_array[:, 1]
print(my_array_column_2)

Operations between arrays

In [ ]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])
suma = a + b # Suma
difference = a - b # Resta
product = a * b # Multiplicación
quotient = a / b # División
print('a = \n',a)
print('\n')
print('b = \n',b)
print('\n')
print('Sum = \n',suma)
print('\n')
print('Difference = \n',difference)
print('\n')
print('Product = \n',product)
print('\n')
print('Quotient = \n',quotient)

In [ ]:
matrix_product = a.dot(b) 
print('Matrix Product = \n', + matrix_product)

dtypes

In [ ]:
my_array = np.empty([2,3], dtype = int)
print(my_array.dtype)

In [ ]:
my_array = np.empty([2,3], dtype = float)
print(my_array.dtype)

In [ ]:
my_array = np.empty([2,3], dtype = float)
print(my_array)
print(my_array.shape)
print(my_array.size)
print(my_array.itemsize)

In [ ]:
my_array = np.empty([2,3], dtype = int)
print(my_array)
print(my_array.shape)
print(my_array.size)
print(my_array.itemsize)

Operations within arrays

In [1]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

In [2]:
a.sum(axis=0)

array([4., 6.])

In [3]:
a.sum(axis=1)

array([3., 7.])

In [4]:
a.min(axis=1)

array([1., 3.])

In [5]:
a.cumsum(axis=0)

array([[1., 2.],
       [4., 6.]])

In [ ]:
np.exp(a)

In [ ]:
np.sqrt(a)

In [ ]:
a.T

Loop using array

In [ ]:
x = np.array([0,1,2,3,4])
for i in x:
    print(i**2)

Stacking arrays

In [ ]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

In [ ]:
a

In [ ]:
b

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

No Copy

In [ ]:
a = np.arange(12)
a

In [ ]:
b = a
b.shape = 3,4
b

In [ ]:
a

View or Shallow Copy

In [ ]:
a = np.arange(12)
a

In [ ]:
c = a.view()
c.shape = 2,6  
c

In [ ]:
a

In [ ]:
c[0,4] = 1234

In [ ]:
a

Deep Copy

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

In [ ]:
d = a.copy()
d[0,0] = 10
print(d)

In [ ]:
a

Indexing and filtering with arrays

In [ ]:
a = np.arange(12)**2 # unidimentional
a

In [ ]:
i = np.array( [ 1,1,3,3,4 ] )
a[i]

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])  # multidimentional
a

In [ ]:
a = np.arange(12, 25, 1)
a

In [ ]:
a[a % 2 == 0] = 0
a

In [ ]:
a[:2]

In [ ]:
a[a < 2] = 10
a

### Pandas (data analysis toolkit)

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

Read csv and excel

In [ ]:
dataset = pd.read_csv('./data/result.csv',
                      sep=';',
                      decimal=',', index_col = 0)

In [ ]:
# For help 
?pd.read_csv

In [ ]:
dataset.head()

In [ ]:
dataset.head(8)

In [ ]:
dataset.tail(2)

In [ ]:
dataset[['var1','target']].head()

In [ ]:
dataset = pd.read_excel('./data/test.xlsx')
dataset.head()

In [ ]:
dataset.dtypes

In [ ]:
dataset['var2'] = dataset['var2'].astype(str)
dataset['var3'] = dataset['var3'].astype(np.float64)
dataset.dtypes

In [ ]:
dataset.to_csv('./data/result.csv',
               sep=';',
               decimal=',')

#### Series

In [ ]:
my_series = pd.Series([2,7,5,10,6])
my_series

In [ ]:
print(my_series.index)
print(my_series.values)

In [ ]:
my_series = pd.Series([2,7,5,10,6], index=['a','b','c','d','e'])
my_series

In [ ]:
my_series.index

In [ ]:
my_series.values

In [ ]:
my_series['c']

Operations

In [ ]:
my_series.std()

In [ ]:
my_series.mean()

In [ ]:
my_series.describe()

In [ ]:
# Percentiles
my_series.quantile(.9)

In [ ]:
print(my_series**2)

In [ ]:
print(np.log(my_series))

In [ ]:
my_series = pd.Series(['a', 'b'])
my_series.mean()

Sampling

In [ ]:
s = pd.Series([10, 1, 8, 3, 45, 5])
s

In [ ]:
s.sample(n=3)

In [ ]:
s.sample(frac=0.5)

In [ ]:
s.sample(n=6, replace=True)

In [ ]:
s.isin([2, 3, 6])

#### Data frame

In [22]:
df1 = pd.read_csv('./data/data_frame1.csv',
                      sep=';',
                      decimal=',', index_col = 1)
df1

student  grade  age  classes
name                                   
maria            1    3.2   23        2
paulo            2    4.5   45        6
john             3    5.4   43        6
mike             4    9.8   23        6
guillermo        5    5.0   21        6
eloisa           6    4.3   21        3
marcus           7    3.5   24        3
mauricio         8    2.3   56        2
natalia          9    4.6   67        5
johanna         10    7.6   34        5
olivia          11    5.7   32        6

General properties

In [ ]:
df1.dtypes

In [ ]:
df1.columns

In [ ]:
df1.loc['maria']

In [ ]:
df1.iloc[0]

In [ ]:
df1.describe()

In [ ]:
df1["classes"].value_counts()

In [ ]:
df1.sort_values(by=["classes", "grade"], ascending = False)

In [ ]:
df1['grade'] >5

In [ ]:
df1.loc[df1['grade'] >5]

In [ ]:
df1.loc[(df1.grade >5) & (df1.classes >5)]

In [23]:
df1.where((df1['grade'] >5) & (df1['classes'] >5))

student  grade   age  classes
name                                    
maria          NaN    NaN   NaN      NaN
paulo          NaN    NaN   NaN      NaN
john           3.0    5.4  43.0      6.0
mike           4.0    9.8  23.0      6.0
guillermo      NaN    NaN   NaN      NaN
eloisa         NaN    NaN   NaN      NaN
marcus         NaN    NaN   NaN      NaN
mauricio       NaN    NaN   NaN      NaN
natalia        NaN    NaN   NaN      NaN
johanna        NaN    NaN   NaN      NaN
olivia        11.0    5.7  32.0      6.0

In [24]:
# np.where(condicion, valor_si, valor_no)

df1["es_juicioso"] = np.where((df1['grade'] > 5), 'si', 'no')
df1

student  grade  age  classes es_juicioso
name                                               
maria            1    3.2   23        2          no
paulo            2    4.5   45        6          no
john             3    5.4   43        6          si
mike             4    9.8   23        6          si
guillermo        5    5.0   21        6          no
eloisa           6    4.3   21        3          no
marcus           7    3.5   24        3          no
mauricio         8    2.3   56        2          no
natalia          9    4.6   67        5          no
johanna         10    7.6   34        5          si
olivia          11    5.7   32        6          si

In [25]:
df1.mask((df1['grade'] >5) & (df1['classes'] >5))

student  grade   age  classes es_juicioso
name                                                
maria          1.0    3.2  23.0      2.0          no
paulo          2.0    4.5  45.0      6.0          no
john           NaN    NaN   NaN      NaN         NaN
mike           NaN    NaN   NaN      NaN         NaN
guillermo      5.0    5.0  21.0      6.0          no
eloisa         6.0    4.3  21.0      3.0          no
marcus         7.0    3.5  24.0      3.0          no
mauricio       8.0    2.3  56.0      2.0          no
natalia        9.0    4.6  67.0      5.0          no
johanna       10.0    7.6  34.0      5.0          si
olivia         NaN    NaN   NaN      NaN         NaN

In [ ]:
df1.query('(grade >5) & (classes >5)')

Grouping, NAs and apply

In [ ]:
df2 = pd.read_csv('./data/data_frame2.csv',
                      sep=';',
                      decimal=',')

In [ ]:
df2

In [ ]:
df2["name"].unique()

In [ ]:
df2[['name','grade']].groupby("name").mean()

In [ ]:
df2[['name','grade']].groupby("name").mean().sort_values(by='grade')

In [ ]:
df2["name"].apply(lambda x: x[:3])

In [ ]:
df2.loc[df2['name']=='maria','grade'] = np.nan
df2

In [ ]:
df2.dropna()

In [ ]:
df2.fillna(0.0)

In [ ]:
df2['student'].isna()

In [ ]:
df2['student'].isna().sum(axis=0)

In [ ]:
df2.isna().sum(axis=0)

In [ ]:
df2.isna().sum(axis=0) / df2.shape[0]

Sampling

In [ ]:
df3 = pd.DataFrame({'col1': [1, 2, 3], 'col2': [2, 3, 4]}, 
                   index = ['a', 'b', 'c'])
df3

In [ ]:
df3.sample(n=2)

In [ ]:
df3.sample(n=1, axis=1)

Duplicated

In [ ]:
df4 = pd.DataFrame({'col1': [1, 2, 1, 1], 'col2': [2, 3, 1, 1]}, index = ['a', 'b', 'c', 'd'])
df4

In [ ]:
df4['col1'].duplicated()

In [ ]:
df4.sort_values(by = 'col2')['col1'].duplicated()

In [ ]:
 df4.duplicated('col1')

In [ ]:
df4.drop_duplicates('col1')

In [ ]:
df4.duplicated(['col1', 'col2'])

In [ ]:
df4_2 = df4.drop_duplicates(['col1', 'col2'])

In [ ]:
df4

Set and reset index

In [ ]:
df1 = pd.read_csv('./data/data_frame1.csv',
                      sep=';',
                      decimal=',')
df1

In [ ]:
df2 = df1.set_index('student')
df2

In [ ]:
df2.loc[1]

In [ ]:
df1.loc[1]

In [ ]:
df2.reset_index()

In [ ]:
df2.reset_index(drop=True)

In [ ]:
df2.index = range(10,21)
df2

Append and concatenate

In [11]:
df1 = pd.read_csv('./data/concat1.csv',
                      sep=';',
                      decimal=',',
                      index_col =0)
df2 = pd.read_csv('./data/concat2.csv',
                      sep=';',
                      decimal=',',
                      index_col ='index')
df3 = pd.read_csv('./data/concat3.csv',
                      sep=';',
                      decimal=',',
                      index_col ='index')

In [13]:
df1

ID   B   C   D
index                
1       1  b1  c1  d1
2       2  b2  c2  d2
3       3  b3  c3  d3
4       4  b4  c4  d4

In [14]:
df2

ID   B   C   D
index                
5       1  b5  c5  d5
6       2  b6  c6  d6
7       3  b7  c7  d7
8       4  b8  c8  d8

In [16]:
df3

ID    B    C    D
index                   
9       1   b9   c9   d9
10      2  b10  c10  d10
11      5  b11  c11  d11

In [15]:
df1.append(df2)

ID   B   C   D
index                
1       1  b1  c1  d1
2       2  b2  c2  d2
3       3  b3  c3  d3
4       4  b4  c4  d4
5       1  b5  c5  d5
6       2  b6  c6  d6
7       3  b7  c7  d7
8       4  b8  c8  d8

In [ ]:
df1.append([df2,df3])

In [ ]:
pd.concat([df1, df2])

In [ ]:
pd.concat([df1, df2], axis=1)

In [ ]:
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)

Merge

In [ ]:
pd.merge(left=df1,
         right=df3,
         how='inner',
         left_on=['ID'],
         right_on=['ID'])

In [ ]:
df1.merge(df3, how = 'inner', left_on = ['ID'], right_on = ['ID'])

In [ ]:
df1.columns = ['ID','B_df1', 'C_df1', 'D_df1']
df3.columns = ['ID','B_df3', 'C_df3', 'D_df3']

In [18]:
df1

ID   B   C   D
index                
1       1  b1  c1  d1
2       2  b2  c2  d2
3       3  b3  c3  d3
4       4  b4  c4  d4

In [19]:
df3

ID    B    C    D
index                   
9       1   b9   c9   d9
10      2  b10  c10  d10
11      5  b11  c11  d11

In [20]:
pd.merge(left=df1,
         right=df3,
         how='inner',
         left_on=['ID'],
         right_on=['ID'])

ID B_x C_x D_x  B_y  C_y  D_y
0   1  b1  c1  d1   b9   c9   d9
1   2  b2  c2  d2  b10  c10  d10

In [21]:
pd.merge(left=df1,
         right=df3,
         how='left',
         left_on=['ID'],
         right_on=['ID'])

ID B_x C_x D_x  B_y  C_y  D_y
0   1  b1  c1  d1   b9   c9   d9
1   2  b2  c2  d2  b10  c10  d10
2   3  b3  c3  d3  NaN  NaN  NaN
3   4  b4  c4  d4  NaN  NaN  NaN

In [ ]:
df1.merge(df3, how = 'left', on = ['ID'])

In [ ]:
pd.merge(left=df1,
         right=df3,
         how='outer')

In [ ]:
df1 = df1.rename(columns = {'ID':'ID_df1'}) #df1.rename(columns = {'ID' : 'ID_df1'}, inplace = True)
df2 = df2.rename(columns = {'ID':'ID_df2'})

In [ ]:
print(df1)
print(df2)

Joining on index

In [ ]:
df2.index = df1.index
df1.join(df2)

In [ ]:
df4 = df1.join(df3, how='outer')
df4

Fill (forward and backward)

In [ ]:
df5 = df4.ffill()
df5

In [ ]:
df6 = df5.bfill()
df6

Plots

In [ ]:
df2 = pd.read_csv('./data/data_frame1.csv',
                      sep=';',
                      decimal=',')

In [ ]:
df2["grade"].plot.hist()

In [ ]:
df2["grade"].plot.hist(bins=20)

In [ ]:
df2["classes"].value_counts().plot.bar()

In [ ]:
df2["classes"].value_counts().plot.barh()

In [ ]:
df2[['name','grade']].groupby('name').mean().plot.barh(title="Grades")

In [ ]:
df2.groupby(["name"])["grade"].mean().plot.barh(title = "Grades")

In [ ]:
df2.plot.scatter(x='age', y='classes')

Date/Time

In [ ]:
import datetime

dti = pd.to_datetime(['1/1/2018', np.datetime64('2018-01-01'), datetime.datetime(2018, 1, 1)])

In [ ]:
dti

In [ ]:
pd.to_datetime(['2009/07/31', 'asd'], errors='coerce')

In [ ]:
s = pd.Series(pd.date_range('2012-1-1', periods=3, freq='D'))
s

In [ ]:
td = pd.Series([pd.Timedelta(days=i) for i in range(3)])
td

In [ ]:
df = pd.DataFrame({'datetime': s, 'timedelta': td})

In [ ]:
df['sum'] = df['datetime']+df['timedelta']
df

In [ ]:
s.shift()

Statistics

In [ ]:
ser = pd.Series(np.random.randn(8))

In [ ]:
ser

In [ ]:
ser.pct_change()

In [ ]:
ser.pct_change(periods=3)

In [ ]:
s1 = pd.Series(np.random.randn(1000))
s2 = pd.Series(np.random.randn(1000))
s1.cov(s2)

In [ ]:
frame = pd.DataFrame(np.random.randn(1000, 5),
                     columns=['a', 'b', 'c', 'd', 'e'])
frame.cov()

In [ ]:
frame.corr()

In [ ]:
s = pd.Series(np.random.randn(1000),
              index=pd.date_range('1/1/2000', periods=1000))

In [ ]:
s

In [ ]:
s = s.cumsum()

In [ ]:
s

In [ ]:
r = s.rolling(window=60)

In [ ]:
r

In [ ]:
r.sum()

In [ ]:
s.plot(style='k--')
r.mean().plot(style='k')

Missing

In [ ]:
df = pd.read_csv('./data/data_missing.csv',
                      sep=';',
                      decimal=',')

In [ ]:
df

In [ ]:
df.isna()

In [ ]:
df['two'].sum()

In [ ]:
df['two'].mean()

In [ ]:
df['three'].cumsum()

In [ ]:
df['three'].cumsum(skipna=False)

In [ ]:
df.fillna(0)

In [ ]:
df.dropna()

Reshaping and pivot tables

In [ ]:
df = pd.read_csv('./data/data_pivot.csv',
                      sep=';',
                      decimal=',')
df

Pivot

In [ ]:
df_pivot = df.pivot(index='date', columns='variable', values='value')
df_pivot

Stack

In [ ]:
df = df.loc[range(3)]
df

In [ ]:
df2 = df.stack()
df2

In [ ]:
df2.index

In [ ]:
df2.unstack(1)

Melt

In [ ]:
df_pivot

In [ ]:
df_pivot.reset_index(inplace=True)
df_pivot

In [ ]:
df_pivot.melt(id_vars=['date'])

Crosstab

In [ ]:
a = np.array(['a', 'b', 'c', 'd'], dtype=object)
b = np.array(['a', 'a', 'a', 'd'], dtype=object)
pd.crosstab(a, b)

Get_dummies

In [ ]:
df = pd.DataFrame({'key': list('bbacab'), 'data1': range(6)})
df

In [ ]:
pd.get_dummies(df['key'])

In [ ]:
df['key_a'] = (df['key'] == 'a')*1
df